package net.lenni0451.optconfig.annotations.internal;

import net.lenni0451.optconfig.annotations.Migrator;
import org.jetbrains.annotations.ApiStatus;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Internal annotation to register multiple migrator classes for a config class.<br>
 * It is automatically generated by the compiler when using the {@link Migrator} annotation.
 */
@ApiStatus.Internal
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface Migrators {

    Migrator[] value();

}
